/** Wire types for the AI-widget (embed config) API. A widget is owned by a business or an
 *  institution — exactly one of the two ids is set. */

import type { MessageAttachment } from "@/components/chat/types";

export type EmbedConfig = {
  id: number;
  business_id: number | null;
  institution_id: number | null;
  embed_key: string;
  display_name: string | null;
  logo_url: string | null;
  brand_color: string | null;
  /** Bottom corner of the launcher on the customer's site. */
  position: WidgetPosition;
  custom_instructions: string | null;
  /** Panel copy: what the counsellor opens with, and the line under its name. */
  greeting: string | null;
  subtitle: string | null;
  monthly_credit_limit: number;
  credits_used_this_month: number;
  month_reset_at: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type WidgetPosition = "left" | "right";

export type CreateEmbedConfigInput = {
  display_name?: string;
  logo_url?: string;
  brand_color?: string;
  position?: WidgetPosition;
  custom_instructions?: string;
  greeting?: string;
  subtitle?: string;
  monthly_credit_limit?: number;
};

/** Appearance edit: omitted = unchanged, null = cleared. */
export type UpdateEmbedConfigInput = {
  display_name?: string | null;
  logo_url?: string | null;
  brand_color?: string | null;
  position?: WidgetPosition;
  custom_instructions?: string | null;
  greeting?: string | null;
  subtitle?: string | null;
  monthly_credit_limit?: number;
};

export type EmbedConfigListResponse = { configs: EmbedConfig[] };

// ── Snippet handoff ──────────────────────────────────────────────────────────
// The portal's AI-embed card: the org's widget (minted on first ask), the tag to paste, and
// whoever the tag gets mailed to.

/** Someone the widget code has been mailed to. NOT a teammate: no account, no role, no invitation
 *  — the whole record is the `ai_embed_developers` row. */
export type DeveloperContact = { id: number; email: string; last_sent_at: string | null; send_count: number };

export type EnsureEmbedResult = {
  config: EmbedConfig;
  /** Built by the backend so the email and the card always show the same string. */
  snippet: string;
  developers: DeveloperContact[];
};

/** Who to mail the code to. Nobody is invited and no account is created, so there is no name. */
export type SendSnippetInput = { emails: string[] };

/** `sent` names only the addresses whose mail was accepted; anything in `failed` was not sent and
 *  was not recorded, so it can simply be sent again. A send where nothing got out is an error
 *  response, never a result with an empty `sent`. `recipients` is the whole list as it stood when
 *  the send read it — merge the `sent` rows out of it, never adopt it wholesale (see the slice). */
export type SendSnippetResult = { sent: string[]; failed: string[]; recipients: DeveloperContact[] };

// ── Widget visitors and leads ────────────────────────────────────────────────
// The people who talked to the widget. Rows come from the OWNING tenant's schema
// (`ai_widget_visitors`), so a business only ever sees its own — the isolation is the
// connection the backend resolves from the token, not a filter this client sends.

/**
 * A stored column on `ai_widget_visitors`, generated by Postgres from whether the person ever
 * left their details (migration 20260923_001). Read-only in every direction: nothing in this
 * client sends it, and the backend accepts it only as a filter.
 */
export type VisitorStatus = "visitor" | "lead";
export type VisitorStatusFilter = VisitorStatus | "all";

/**
 * One self-reported qualification / test / job, as the assistant extracted it from the
 * conversation. Loosely typed on purpose: the field names mirror the platform_user_* tables,
 * but the values are a model's reading of a stranger's prose, so the UI shows them as
 * "what they told the assistant" and never as a record.
 */
export type VisitorProfileEntry = Record<string, string | boolean | Record<string, string> | undefined>;

export type WidgetVisitor = {
  id: number;
  embed_config_id: number;
  session_id: number | null;
  /** Null for everyone who never handed over their details — the anonymous majority. */
  name: string | null;
  email: string | null;
  phone: string | null;
  /**
   * How we came to hold these details. "volunteered" means the counsellor read them out of what
   * the visitor typed; "card" means they filled the form in. Null when we hold none.
   */
  contact_source: "card" | "volunteered" | null;
  status: VisitorStatus;
  contact_status: "not_shown" | "shown" | "skipped" | "submitted";
  contact_submitted_at: string | null;
  conversation_state: "active" | "ending_prompt_shown" | "continue" | "end_confirmed";
  message_count: number;
  first_seen_at: string;
  last_activity_at: string;
  qualifications: VisitorProfileEntry[] | null;
  language_tests: VisitorProfileEntry[] | null;
  academic_tests: VisitorProfileEntry[] | null;
  work_experiences: VisitorProfileEntry[] | null;
  /**
   * Scalar attributes, same provenance as the arrays above: stated by the visitor, extracted from
   * the conversation, never inferred from a name or a language.
   *
   * `age` is VERBATIM ("22", "early 30s") — there is no age-group list behind it, so never render
   * it as a bucket or a range. `nationality` is a resolved country name; `nationality_raw` is the
   * visitor's own wording, present only when it differed or matched no country.
   * `study_preference` is the one course being discussed.
   */
  age: string | null;
  gender: string | null;
  nationality: string | null;
  nationality_raw: string | null;
  study_preference: string | null;
  summary_status: "pending" | "processing" | "sent" | "failed" | null;
  summary_sent_at: string | null;
  /** When the visitor ended the chat. Optional until every tenant has the column in the list. */
  end_confirmed_at?: string | null;
  /** End-of-chat faces, 1 (😞) to 5 (😍), and the optional "what could we do better". */
  rating?: number | null;
  rating_comment?: string | null;
  rated_at?: string | null;
  /**
   * Written for staff by the summary worker, for every chat: first after 30 quiet minutes, then
   * at most daily and only if there was activity since. `text` is null when the chat was too short.
   */
  /** The CONTACT summary: the whole person, from their profile and every chat's summary. */
  summary?: StaffSummary | null;
} & ConversationControl;

/** A staff-facing summary — a visitor's contact summary, or one chat's own. */
export type StaffSummary = {
  /** Chat summaries only: a few words naming the topic ("Scholarships for the MEng"). */
  title?: string | null;
  /** One or two sentences; `**bold**` marks the key facts. */
  text: string | null;
  /** Topics the student raised that are still unanswered. */
  open?: string[];
  next_step?: string | null;
  /** The course the chat (or the most recent chat) ended on. */
  program?: { name: string; city?: string | null } | null;
  topics?: string[];
  /** Contact summaries only: what it was built from. */
  chat_count?: number;
  detail_count?: number;
  generated_at?: string;
};

/** One chat with the widget. Ending it closes it; the visitor's next visit starts a new one. */
export type VisitorChat = {
  id: number;
  started_at: string;
  ended_at: string | null;
  message_count: number;
  /** Refreshed after every message. Null until the chat has a real exchange. */
  summary: StaffSummary | null;
};

/** Tally per tab, honouring the current search — so a tab never promises rows it won't show. */
export type VisitorCounts = Record<VisitorStatusFilter, number>;

export type VisitorListParams = {
  page?: number;
  limit?: number;
  search?: string;
  status?: VisitorStatusFilter;
};

export type VisitorListResult = { data: WidgetVisitor[]; total: number; counts: VisitorCounts };

/**
 * What a business or institution may correct on a visitor row.
 *
 * Only the things the visitor stated about themselves. The activity record (message counts,
 * timestamps, contact and summary state) is the widget's, and `status` is computed by Postgres
 * from name/email — the backend rejects any key outside this shape rather than ignoring it.
 *
 * `null` clears a field; a key left out is untouched. Name and email must move TOGETHER — the
 * the card asks for both and its copy promises a summary, which needs an address — so both
 * keys are sent, or neither. (The DB no longer forbids a half contact: details a visitor
 * volunteers in conversation can arrive one at a time.)
 */
export type VisitorPatch = {
  name?: string | null;
  email?: string | null;
  age?: string | null;
  gender?: string | null;
  nationality?: string | null;
  study_preference?: string | null;
  /**
   * A record section, replaced WHOLESALE — add, edit and delete are all "here is the new list".
   * Entry keys are the Personal Profile popups' fields and nothing else; the backend rejects
   * anything outside that set rather than storing it.
   */
  qualifications?: VisitorProfileEntry[];
  work_experiences?: VisitorProfileEntry[];
  language_tests?: VisitorProfileEntry[];
  academic_tests?: VisitorProfileEntry[];
};

/** The four editable record sections, by the key each is stored under. */
export type VisitorRecordSection = "qualifications" | "work_experiences" | "language_tests" | "academic_tests";

/**
 * Who wrote a turn: the visitor, the AI assistant, or a staff member who took the chat over.
 * `agent` is set by the server from the token — the client never says who it is.
 */
export type VisitorMessageRole = "user" | "assistant" | "agent";

/** One turn of a visitor's chat, as the Inbox's AI Conversations transcript shows it. */
export type VisitorMessage = {
  id: number;
  role: VisitorMessageRole;
  content: string;
  created_at: string;
  /** Agent turns only: the staff member's name, saved on the message when it was sent. */
  sender_name?: string | null;
  /** Agent turns only. Signed URLs, like enquiry chat attachments. */
  attachments?: MessageAttachment[];
  /** Which chat this message belongs to. */
  session_id?: number;
  /** Set on a chat's first message in the transcript, so the Inbox can draw a divider there. */
  chat?: VisitorChat;
};

/**
 * Who is answering a widget chat, and whether staff have closed it.
 *
 * Optional on the wire until the takeover backend ships: a row without these fields reads as
 * "the AI is handling it, nothing unread, not resolved" — exactly what the widget does today.
 */
export type ConversationControl = {
  /** Null → the AI assistant answers. Set → it stays silent and this person answers. */
  handled_by_user_id?: number | null;
  handled_by_name?: string | null;
  /** The server's answer to "is that me?" — the auth state carries no user id to compare. */
  handled_by_me?: boolean;
  /** The handler's last activity. The server hands the chat back to the AI 15 minutes after it. */
  handled_at?: string | null;
  /** The visitor asked for a person and nobody has joined yet. The AI is paused meanwhile. */
  handoff_requested_at?: string | null;
  resolved_at?: string | null;
  resolved_by_name?: string | null;
  /** Visitor messages since staff last opened or answered. One counter per org. */
  unread_count?: number;
};

/**
 * A staff-only note on a visitor. Never reaches the visitor or the AI — it lives in its own
 * table, not in the transcript. Shown inline in the Inbox, interleaved by time.
 */
export type VisitorNote = {
  id: number;
  author_name: string;
  content: string;
  /** Signed URLs, like a staff reply's. Absent on a schema behind 20261002_002. */
  attachments?: MessageAttachment[];
  created_at: string;
};

export type SendVisitorMessageResult = { message: VisitorMessage; control: ConversationControl };
export type ConversationControlResult = { control: ConversationControl };
export type HandoffMode = "human" | "ai";
