/** Wire types for the AI-widget (embed config) API. A widget is owned by a business or an
 *  institution — exactly one of the two ids is set. */

export type EmbedConfig = {
  id: number;
  business_id: number | null;
  institution_id: number | null;
  embed_key: string;
  display_name: string | null;
  logo_url: string | null;
  brand_color: string | null;
  custom_instructions: string | null;
  monthly_credit_limit: number;
  credits_used_this_month: number;
  month_reset_at: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type CreateEmbedConfigInput = {
  display_name?: string;
  logo_url?: string;
  brand_color?: string;
  custom_instructions?: string;
  monthly_credit_limit?: number;
};

export type EmbedConfigListResponse = { configs: EmbedConfig[] };

// ── Widget visitors and leads ────────────────────────────────────────────────
// The people who talked to the widget. Rows come from the OWNING tenant's schema
// (`ai_widget_visitors`), so a business only ever sees its own — the isolation is the
// connection the backend resolves from the token, not a filter this client sends.

/**
 * A stored column on `ai_widget_visitors`, generated by Postgres from whether the person ever
 * left their details (migration 20260923_001). Read-only in every direction: nothing in this
 * client sends it, and the backend accepts it only as a filter.
 */
export type VisitorStatus = "visitor" | "lead";
export type VisitorStatusFilter = VisitorStatus | "all";

/**
 * One self-reported qualification / test / job, as the assistant extracted it from the
 * conversation. Loosely typed on purpose: the field names mirror the platform_user_* tables,
 * but the values are a model's reading of a stranger's prose, so the UI shows them as
 * "what they told the assistant" and never as a record.
 */
export type VisitorProfileEntry = Record<string, string | boolean | Record<string, string> | undefined>;

export type WidgetVisitor = {
  id: number;
  embed_config_id: number;
  session_id: number | null;
  /** Null for everyone who never handed over their details — the anonymous majority. */
  name: string | null;
  email: string | null;
  status: VisitorStatus;
  contact_status: "not_shown" | "shown" | "skipped" | "submitted";
  contact_submitted_at: string | null;
  conversation_state: "active" | "ending_prompt_shown" | "continue" | "end_confirmed";
  message_count: number;
  first_seen_at: string;
  last_activity_at: string;
  qualifications: VisitorProfileEntry[] | null;
  language_tests: VisitorProfileEntry[] | null;
  academic_tests: VisitorProfileEntry[] | null;
  work_experiences: VisitorProfileEntry[] | null;
  /**
   * Scalar attributes, same provenance as the arrays above: stated by the visitor, extracted from
   * the conversation, never inferred from a name or a language.
   *
   * `age` is VERBATIM ("22", "early 30s") — there is no age-group list behind it, so never render
   * it as a bucket or a range. `nationality` is a resolved country name; `nationality_raw` is the
   * visitor's own wording, present only when it differed or matched no country.
   * `study_preference` is the one course being discussed.
   */
  age: string | null;
  gender: string | null;
  nationality: string | null;
  nationality_raw: string | null;
  study_preference: string | null;
  summary_status: "pending" | "processing" | "sent" | "failed" | null;
  summary_sent_at: string | null;
};

/** Tally per tab, honouring the current search — so a tab never promises rows it won't show. */
export type VisitorCounts = Record<VisitorStatusFilter, number>;

export type VisitorListParams = {
  page?: number;
  limit?: number;
  search?: string;
  status?: VisitorStatusFilter;
};

export type VisitorListResult = { data: WidgetVisitor[]; total: number; counts: VisitorCounts };

/**
 * What a business or institution may correct on a visitor row.
 *
 * Only the things the visitor stated about themselves. The activity record (message counts,
 * timestamps, contact and summary state) is the widget's, and `status` is computed by Postgres
 * from name/email — the backend rejects any key outside this shape rather than ignoring it.
 *
 * `null` clears a field; a key left out is untouched. Name and email must move TOGETHER — the
 * table's CHECK forbids half a contact — so both keys are sent, or neither.
 */
export type VisitorPatch = {
  name?: string | null;
  email?: string | null;
  age?: string | null;
  gender?: string | null;
  nationality?: string | null;
  study_preference?: string | null;
  /**
   * A record section, replaced WHOLESALE — add, edit and delete are all "here is the new list".
   * Entry keys are the Personal Profile popups' fields and nothing else; the backend rejects
   * anything outside that set rather than storing it.
   */
  qualifications?: VisitorProfileEntry[];
  work_experiences?: VisitorProfileEntry[];
  language_tests?: VisitorProfileEntry[];
  academic_tests?: VisitorProfileEntry[];
};

/** The four editable record sections, by the key each is stored under. */
export type VisitorRecordSection = "qualifications" | "work_experiences" | "language_tests" | "academic_tests";

/** One turn of a visitor's chat with the assistant — the Inbox's read-only AI Embed transcript. */
export type VisitorMessage = {
  id: number;
  role: "user" | "assistant";
  content: string;
  created_at: string;
};
