name: Build & Push backend

on:
  push:
    branches:
      - 'main'
      - 'production'
      - 'staging'
      - 'develop'

    paths:
      - "backend/**"

env:
  RED_COLOR_MESSAGE: "\e[31m"
  GREEN_COLOR_MESSAGE: "\e[32m"
  YELLOW_COLOR_MESSAGE: "\e[33m"
  RESET_COLOR_MESSAGE: "\e[0m"
  SERVICE_NAME: "backend"

concurrency:
  group: build-push-backend-${{ github.ref }}
  cancel-in-progress: false

jobs:
  resolve-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Resolve environment
        run: |
          printf "\n\n =======================================================================\n"
          if [[ "${{ github.event_name }}" == "push" && ("${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/production") ]]; then
            echo "env_name=production" >> $GITHUB_ENV
            echo "Selected environment: ${{ env.GREEN_COLOR_MESSAGE }} production ${{ env.RESET_COLOR_MESSAGE }}"
          elif [[ "${{ github.event_name }}" == "push" && ("${{ github.ref }}" == "refs/heads/develop" || "${{ github.ref }}" == "refs/heads/staging") ]]; then
            echo "env_name=staging" >> $GITHUB_ENV
            echo "Selected environment: ${{ env.GREEN_COLOR_MESSAGE }} staging ${{ env.RESET_COLOR_MESSAGE }}"
          else
            echo "env_name=staging" >> $GITHUB_ENV
            echo "Selected environment: ${{ env.GREEN_COLOR_MESSAGE }} staging ${{ env.RESET_COLOR_MESSAGE }}"
          fi

      - name: Verify Deployment Directories
        run: |
          echo "Environment is: ${{ env.env_name }}"

    outputs:
      env_name: ${{ env.env_name }}

  ci-build:
    runs-on: ubuntu-latest
    name: Install,Build for => ${{ needs.resolve-env.outputs.env_name }}
    needs: [resolve-env]
    environment: ${{ needs.resolve-env.outputs.env_name }}
    timeout-minutes: 25
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Dynamic Initializing Variables
        run: |
          TAG="$(date +'%m-%d')-$(git rev-parse --short HEAD)"
          REGION="${{ vars.GCP_REGION }}"
          IMAGE="${REGION}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}/${{ env.SERVICE_NAME }}"

          echo "Image tag = ${TAG}"
          echo "Image path = ${IMAGE}"

          echo "REGION=${REGION}" >> $GITHUB_ENV
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ env.SERVICE_NAME }}-${TAG}" >> $GITHUB_ENV

      - name: Configure docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet



      - name: Checking variables value
        run: |
          echo "Image tag :${{ env.GREEN_COLOR_MESSAGE }} ${{ env.IMAGE_TAG }} ${{ env.RESET_COLOR_MESSAGE }} "
          echo "Registry : ${{ env.GREEN_COLOR_MESSAGE }} ${{ env.IMAGE }} ${{ env.RESET_COLOR_MESSAGE }}" 

      - name: Build, tag, and push the image to Artifact Registry
        working-directory: backend
        run: |
          echo "${{ env.YELLOW_COLOR_MESSAGE }} Prequities setup ${{ env.RESET_COLOR_MESSAGE }}"
          cp -r "${{ github.workspace }}/devops/nginx" devops-tmp/nginx
          gcloud storage cp ${{ vars.ENV_BUCKET  }}/backend/.env "${{ github.workspace }}/backend/.env"
          gcloud storage cp ${{ vars.ENV_BUCKET  }}/backend/gcp-service-account-key.json "${{ github.workspace }}/backend/gcp-service-account-key.json"


          echo "${{ env.YELLOW_COLOR_MESSAGE }} Building docker image ${{ env.RESET_COLOR_MESSAGE }}"
          docker build -f Dockerfile -t "${{ env.IMAGE }}:${{ env.IMAGE_TAG }}" .

          echo "${{ env.YELLOW_COLOR_MESSAGE }} Tagging docker image as latest ${{ env.RESET_COLOR_MESSAGE }}"
          docker tag "${{ env.IMAGE }}:${{ env.IMAGE_TAG }}" "${{ env.IMAGE }}:latest"

          echo "${{ env.GREEN_COLOR_MESSAGE }} Pushing docker image ${{ env.RESET_COLOR_MESSAGE }}"
          docker push "${{ env.IMAGE }}:${{ env.IMAGE_TAG }}"
          docker push "${{ env.IMAGE }}:latest"

    outputs:
      BUILD_IMAGE_TAG: ${{ env.IMAGE_TAG }}
      BUILD_IMAGE: ${{ env.IMAGE }}
      BUILD_REGION: ${{ env.REGION }}

  cd-release:
    runs-on: ubuntu-latest
    name: Release for => ${{ needs.resolve-env.outputs.env_name }}
    needs:
      - resolve-env
      - ci-build
    environment: ${{ needs.resolve-env.outputs.env_name }}
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dynamic Initializing Variables
        run: |
          echo "IMAGE_TAG=${{ needs.ci-build.outputs.BUILD_IMAGE_TAG }}" >> $GITHUB_ENV
          
      - name: Checking value of Initialized Variables
        run: |     
          echo "IMAGE_TAG: ${{ env.IMAGE_TAG }}"   

      - name: Update image tag in GitOps repo
        env:
           GITOPS_REPO: https://x-access-token:${{ secrets.WRITE_TOKEN_GITHUB }}@${{ vars.GITOPS_REPO }}
           GITOPS_BRANCH: ${{ vars.GITOPS_BRANCH }}   # or 'staging' if your GitOps repo uses an env branch
           VALUES_FILE_PATH: ${{ vars.VALUES_FILE_PATH }}/apps
           GIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name || github.actor }}
           GIT_AUTHOR_EMAIL: ${{ github.event.head_commit.author.email || format('{0}@users.noreply.github.com', github.actor) }}
        run: |
           echo "🛠️ Cloning GitOps repo..."
           git clone --single-branch --branch "${GITOPS_BRANCH}" "${GITOPS_REPO}" repo
           cd repo

           echo "Updating image tag in $VALUES_FILE_PATH..."
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/api-globalyapp.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-auth.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-business-claim-requests.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-import-v2.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-extraction-agentcis.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-extraction-pages.yml"                                 
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-extraction-schedule.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-extraction-step.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-extraction-verify.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-extraction.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-scholarship-import.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-scholarship-bulk-delete.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-ai-knowledge-crawl.yml"
           sed -i "s|^\(\s*tag:\s*\).*|\1${IMAGE_TAG}|" "${VALUES_FILE_PATH}/workers/worker-ai-knowledge-recrawl.yml"

           echo "updating globalyapp-images..."
           ## git config user.name "devops-github-actions"
           ## git config user.email "devops-github-actions@github.com"

           echo "Committing as: ${GIT_AUTHOR_NAME} <${GIT_AUTHOR_EMAIL}>"
           git config user.name "${GIT_AUTHOR_NAME}"
           git config user.email "${GIT_AUTHOR_EMAIL}"
           git add "${VALUES_FILE_PATH}"
           git commit -m "globalyapp backend releases with ${IMAGE_TAG}"
           git push origin "${GITOPS_BRANCH}"